# Generated by Django 4.2.13 on 2026-09-15 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action effectuée')),
                ('target_object', models.CharField(blank=True, default='', max_length=255, verbose_name='Objet ciblé')),
                ('ip_address', models.CharField(blank=True, default='', max_length=50, verbose_name='Adresse IP')),
                ('status', models.CharField(default='SUCCESS', max_length=20, verbose_name='Résultat Action')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails non sensibles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='companies.company', verbose_name='Entreprise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]
