# Generated by Django 4.2.13 on 2026-09-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Paramétrage standard', max_length=100, verbose_name='Libellé')),
                ('prefix', models.CharField(default='FAC-2026-', max_length=20, verbose_name='Préfixe Factures')),
                ('credit_note_prefix', models.CharField(default='AV-2026-', max_length=20, verbose_name='Préfixe Avoirs')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro de facture')),
                ('next_credit_note_number', models.PositiveIntegerField(default=1, verbose_name="Prochain numéro d'avoir")),
                ('default_currency', models.CharField(default='GNF', max_length=10, verbose_name='Devise')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA par défaut (%)')),
                ('legal_mentions', models.TextField(default='Facture établie conformément à la réglementation fiscale en vigueur.', verbose_name='Mentions légales')),
                ('payment_conditions', models.TextField(default="Paiement à 30 jours à compter de la date d'émission.", verbose_name='Conditions de paiement')),
                ('payment_instructions', models.TextField(default='Virement bancaire au compte inscrit sur la facture.', verbose_name='Instructions de paiement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Entreprise associée au paramétrage.', on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Paramétrage de facturation',
                'verbose_name_plural': 'Paramétrages de facturation',
            },
        ),
    ]
