# Generated by Django 4.2.13 on 2026-09-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=255, verbose_name='Raison Sociale')),
                ('nif', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'Identification Fiscale (NIF)")),
                ('rccm', models.CharField(blank=True, default='', max_length=100, verbose_name='RCCM')),
                ('address', models.TextField(verbose_name='Adresse siège social')),
                ('phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('fiscal_regime', models.CharField(blank=True, default='Régime Réel', max_length=100, verbose_name='Régime Fiscal')),
                ('tax_center', models.CharField(blank=True, default='', max_length=100, verbose_name='Centre des Impôts')),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_iban', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
    ]
