# Generated by Django 4.2.13 on 2026-09-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom / Raison Sociale')),
                ('nifp', models.CharField(blank=True, default='', max_length=50, verbose_name='NIF / NIFp Client')),
                ('rccm', models.CharField(blank=True, default='', max_length=100, verbose_name='RCCM Client')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('city', models.CharField(blank=True, default='Conakry', max_length=100, verbose_name='Ville')),
                ('country', models.CharField(blank=True, default='Guinée', max_length=100, verbose_name='Pays')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Entreprise associée au client.', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-id'],
            },
        ),
    ]
