# Generated by Django 4.2.13 on 2026-09-15 12:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='BROUILLON', max_length=100, verbose_name="Numéro d'avoir")),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('reason', models.TextField(verbose_name="Motif d'émission de l'avoir")),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validée'), ('TRANSMITTED', 'En transmission'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Rejetée'), ('ERROR', 'Erreur')], default='DRAFT', max_length=20, verbose_name='Statut Avoir')),
                ('etva_status', models.CharField(choices=[('PENDING', 'Non transmise'), ('TRANSMITTED', 'Transmise'), ('ACCEPTED', 'Acceptée DGI'), ('REJECTED', 'Rejetée DGI'), ('ERROR', 'Erreur technique')], default='PENDING', max_length=20, verbose_name='Statut eTVA')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total TTC')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='companies.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='customers.customer', verbose_name='Client')),
                ('parent_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoices.invoice', verbose_name="Facture d'origine")),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix unitaire HT')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('line_total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Ligne HT')),
                ('line_vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant TVA Ligne')),
                ('line_total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Ligne TTC')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='credit_notes.creditnote', verbose_name='Avoir')),
            ],
            options={
                'verbose_name': "Ligne d'avoir",
                'verbose_name_plural': "Lignes d'avoir",
            },
        ),
    ]
