# Generated by Django 4.2.13 on 2026-09-15 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit_notes', '0001_initial'),
        ('companies', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETVATransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox / Démo'), ('HOMOLOGATION', 'Homologation DGI'), ('PRODUCTION', 'Production')], default='SANDBOX', max_length=20, verbose_name='Environnement')),
                ('status', models.CharField(choices=[('SUCCESS', 'Transmis & Validé DGI'), ('REJECTED', 'Rejeté par la DGI'), ('ERROR', 'Erreur Technique'), ('PENDING', 'En cours de traitement')], default='PENDING', max_length=20, verbose_name='Statut Transmission')),
                ('external_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence DGI / Signin')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='Code HTTP')),
                ('response_message', models.TextField(blank=True, default='', verbose_name='Message API')),
                ('response_payload', models.TextField(blank=True, default='', verbose_name='Données Réponse API (Masquées)')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='Durée de la requête (ms)')),
                ('transmitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de transmission')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etva_transmissions', to='companies.company', verbose_name='Entreprise')),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etva_transmissions', to='credit_notes.creditnote', verbose_name='Avoir')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etva_transmissions', to='invoices.invoice', verbose_name='Facture')),
                ('transmitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Transmis par')),
            ],
            options={
                'verbose_name': 'Journal Transmission eTVA',
                'verbose_name_plural': 'Journaux Transmissions eTVA',
                'ordering': ['-transmitted_at'],
            },
        ),
    ]
