# Generated by Django 4.2.13 on 2026-09-15 12:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='BROUILLON', max_length=100, verbose_name='Numéro de facture')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de facturation')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validée'), ('TRANSMITTED', 'En transmission'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Rejetée'), ('ERROR', 'Erreur')], default='DRAFT', max_length=20, verbose_name='Statut Facture')),
                ('etva_status', models.CharField(choices=[('PENDING', 'Non transmise'), ('TRANSMITTED', 'Transmise'), ('ACCEPTED', 'Acceptée DGI'), ('REJECTED', 'Rejetée DGI'), ('ERROR', 'Erreur technique')], default='PENDING', max_length=20, verbose_name='Statut eTVA')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total TTC')),
                ('legal_mentions', models.TextField(blank=True, default='', verbose_name='Mentions légales')),
                ('payment_conditions', models.TextField(blank=True, default='', verbose_name='Conditions de paiement')),
                ('payment_instructions', models.TextField(blank=True, default='', verbose_name='Instructions de paiement')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes internes / Remarques')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.billingsettings', verbose_name='Paramétrage')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix unitaire HT')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('line_total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Ligne HT')),
                ('line_vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant TVA Ligne')),
                ('line_total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Ligne TTC')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='Facture')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='products.product', verbose_name='Produit / Service source')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]
