/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspaceRouteImport } from './routes/_espace'
import { Route as EspaceAvoirsRouteImport } from './routes/_espace.avoirs'
import { Route as EspaceClientsRouteImport } from './routes/_espace.clients'
import { Route as EspaceFacturesRouteImport } from './routes/_espace.factures'
import { Route as EspaceProduitsRouteImport } from './routes/_espace.produits'
import { Route as EspaceTableauDeBordRouteImport } from './routes/_espace.tableau-de-bord'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/_espace',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceAvoirsRoute = EspaceAvoirsRouteImport.update({
  id: '/avoirs',
  path: '/avoirs',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceClientsRoute = EspaceClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceFacturesRoute = EspaceFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceProduitsRoute = EspaceProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceTableauDeBordRoute = EspaceTableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => EspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avoirs': typeof EspaceAvoirsRoute
  '/clients': typeof EspaceClientsRoute
  '/factures': typeof EspaceFacturesRoute
  '/produits': typeof EspaceProduitsRoute
  '/tableau-de-bord': typeof EspaceTableauDeBordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avoirs': typeof EspaceAvoirsRoute
  '/clients': typeof EspaceClientsRoute
  '/factures': typeof EspaceFacturesRoute
  '/produits': typeof EspaceProduitsRoute
  '/tableau-de-bord': typeof EspaceTableauDeBordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_espace': typeof EspaceRouteWithChildren
  '/_espace/avoirs': typeof EspaceAvoirsRoute
  '/_espace/clients': typeof EspaceClientsRoute
  '/_espace/factures': typeof EspaceFacturesRoute
  '/_espace/produits': typeof EspaceProduitsRoute
  '/_espace/tableau-de-bord': typeof EspaceTableauDeBordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avoirs'
    | '/clients'
    | '/factures'
    | '/produits'
    | '/tableau-de-bord'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avoirs'
    | '/clients'
    | '/factures'
    | '/produits'
    | '/tableau-de-bord'
  id:
    | '__root__'
    | '/'
    | '/_espace'
    | '/_espace/avoirs'
    | '/_espace/clients'
    | '/_espace/factures'
    | '/_espace/produits'
    | '/_espace/tableau-de-bord'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EspaceRoute: typeof EspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_espace': {
      id: '/_espace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_espace/avoirs': {
      id: '/_espace/avoirs'
      path: '/avoirs'
      fullPath: '/avoirs'
      preLoaderRoute: typeof EspaceAvoirsRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/clients': {
      id: '/_espace/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof EspaceClientsRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/factures': {
      id: '/_espace/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof EspaceFacturesRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/produits': {
      id: '/_espace/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof EspaceProduitsRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/tableau-de-bord': {
      id: '/_espace/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof EspaceTableauDeBordRouteImport
      parentRoute: typeof EspaceRoute
    }
  }
}

interface EspaceRouteChildren {
  EspaceAvoirsRoute: typeof EspaceAvoirsRoute
  EspaceClientsRoute: typeof EspaceClientsRoute
  EspaceFacturesRoute: typeof EspaceFacturesRoute
  EspaceProduitsRoute: typeof EspaceProduitsRoute
  EspaceTableauDeBordRoute: typeof EspaceTableauDeBordRoute
}

const EspaceRouteChildren: EspaceRouteChildren = {
  EspaceAvoirsRoute: EspaceAvoirsRoute,
  EspaceClientsRoute: EspaceClientsRoute,
  EspaceFacturesRoute: EspaceFacturesRoute,
  EspaceProduitsRoute: EspaceProduitsRoute,
  EspaceTableauDeBordRoute: EspaceTableauDeBordRoute,
}

const EspaceRouteWithChildren =
  EspaceRoute._addFileChildren(EspaceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EspaceRoute: EspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
