# Generated by Django 4.2.13 on 2026-09-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('category', models.CharField(choices=[('PRODUIT', 'Produit'), ('SERVICE', 'Service')], default='SERVICE', max_length=20, verbose_name='Type / Catégorie')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix unitaire HT')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('unit', models.CharField(default='UNITE', max_length=20, verbose_name='Unité de mesure')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Entreprise propriétaire du produit/service.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
            ],
            options={
                'verbose_name': 'Produit / Service',
                'verbose_name_plural': 'Produits & Services',
                'ordering': ['reference', 'designation'],
                'unique_together': {('company', 'reference')},
            },
        ),
    ]
