/**
 * DONNÉES DE DÉMONSTRATION — fictives.
 * Elles sont remplacées par les données de l'API Django dès que VITE_API_URL est configurée.
 */
import type {
  AuditEntry,
  BillingSetting,
  Company,
  Customer,
  EtvaTransmission,
  Invoice,
  Product,
  User,
} from "./types";

const COMPANY_ID = "cmp-1";

export const demoCompany: Company = {
  id: COMPANY_ID,
  name: "GDS Guinée SARL",
  legal_form: "SARL",
  nif: "123456789",
  rccm: "GN-CNK-2019-B-01234",
  address: "Immeuble Kaloum Center, 3e étage",
  city: "Conakry",
  country: "Guinée",
  phone: "+224 622 00 00 00",
  email: "contact@gds-guinee.com",
  website: "https://gds-guinee.com",
  tax_regime: "Réel normal",
  bank_name: "Banque Centrale Populaire",
  bank_account: "GN00 1234 5678 9012 3456",
};

export const demoUsers: User[] = [
  {
    id: "usr-1",
    full_name: "Fatima Sow",
    email: "admin@gds.gn",
    role: "admin",
    company_id: COMPANY_ID,
    is_active: true,
  },
  {
    id: "usr-2",
    full_name: "Mamadou Barry",
    email: "facturier@gds.gn",
    role: "facturier",
    company_id: COMPANY_ID,
    is_active: true,
  },
  {
    id: "usr-3",
    full_name: "Aïssatou Diallo",
    email: "lecture@gds.gn",
    role: "consultation",
    company_id: COMPANY_ID,
    is_active: true,
  },
];

export const demoCustomers: Customer[] = [
  {
    id: "cus-1",
    company_id: COMPANY_ID,
    name: "Société Minière de Boké",
    nifp: "P-100234567",
    contact_name: "Ibrahima Camara",
    phone: "+224 620 11 22 33",
    email: "achats@smb.gn",
    address: "Zone industrielle, Boké",
    city: "Boké",
    is_active: true,
    created_at: "2026-01-12T09:00:00Z",
  },
  {
    id: "cus-2",
    company_id: COMPANY_ID,
    name: "Télécom Guinée SA",
    nifp: "P-100987654",
    contact_name: "Mariama Bah",
    phone: "+224 628 44 55 66",
    email: "fournisseurs@telecomgn.com",
    address: "Avenue de la République",
    city: "Conakry",
    is_active: true,
    created_at: "2026-02-03T10:30:00Z",
  },
  {
    id: "cus-3",
    company_id: COMPANY_ID,
    name: "Clinique Ambroise Paré",
    nifp: "P-100445566",
    contact_name: "Dr. Sékou Touré",
    phone: "+224 664 77 88 99",
    email: "administration@clinique-ap.gn",
    address: "Ratoma, Conakry",
    city: "Conakry",
    is_active: true,
    created_at: "2026-03-21T14:15:00Z",
  },
  {
    id: "cus-4",
    company_id: COMPANY_ID,
    name: "Coopérative Agricole du Fouta",
    nifp: "P-100778899",
    contact_name: "Alpha Oumar Diallo",
    phone: "+224 655 12 34 56",
    email: "caf@fouta-agri.gn",
    address: "Labé centre",
    city: "Labé",
    is_active: false,
    created_at: "2026-04-08T08:45:00Z",
  },
];

export const demoProducts: Product[] = [
  {
    id: "prd-1",
    company_id: COMPANY_ID,
    reference: "SRV-001",
    label: "Développement applicatif (jour/homme)",
    kind: "service",
    unit_price: 2500000,
    vat_rate: 18,
    unit: "jour",
    is_active: true,
  },
  {
    id: "prd-2",
    company_id: COMPANY_ID,
    reference: "SRV-002",
    label: "Maintenance logicielle mensuelle",
    kind: "service",
    unit_price: 4500000,
    vat_rate: 18,
    unit: "mois",
    is_active: true,
  },
  {
    id: "prd-3",
    company_id: COMPANY_ID,
    reference: "PRD-010",
    label: "Ordinateur portable professionnel",
    kind: "produit",
    unit_price: 12500000,
    vat_rate: 18,
    unit: "unité",
    is_active: true,
  },
  {
    id: "prd-4",
    company_id: COMPANY_ID,
    reference: "PRD-011",
    label: "Licence annuelle suite bureautique",
    kind: "produit",
    unit_price: 1800000,
    vat_rate: 18,
    unit: "licence",
    is_active: true,
  },
  {
    id: "prd-5",
    company_id: COMPANY_ID,
    reference: "SRV-003",
    label: "Formation utilisateurs",
    kind: "service",
    unit_price: 1200000,
    vat_rate: 0,
    unit: "session",
    is_active: true,
  },
];

export const demoBillingSettings: BillingSetting[] = [
  {
    id: "bst-1",
    company_id: COMPANY_ID,
    reference: "PARAM-STD",
    label: "Paramétrage standard",
    legal_mentions:
      "Facture émise conformément à la réglementation fiscale en vigueur en République de Guinée. Tout retard de paiement entraîne des pénalités au taux légal.",
    payment_instructions:
      "Règlement par virement bancaire sous 30 jours. Merci d'indiquer la référence de la facture en objet du virement.",
    is_active: true,
  },
  {
    id: "bst-2",
    company_id: COMPANY_ID,
    reference: "PARAM-EXPORT",
    label: "Paramétrage export / exonéré",
    legal_mentions: "Opération exonérée de TVA — justificatif d'exonération conservé au dossier.",
    payment_instructions: "Règlement par lettre de crédit documentaire à 45 jours.",
    is_active: true,
  },
];

function line(
  id: string,
  product_id: string | null,
  description: string,
  quantity: number,
  unit_price: number,
  vat_rate: number,
) {
  return { id, product_id, description, quantity, unit_price, vat_rate };
}

export const demoInvoices: Invoice[] = [
  {
    id: "inv-1",
    company_id: COMPANY_ID,
    document_type: "facture",
    parent_invoice_id: null,
    reference: "FACT-2026-0001",
    internal_reference: "CMD-SMB-014",
    customer_id: "cus-1",
    billing_setting_id: "bst-1",
    issue_date: "2026-07-02",
    due_date: "2026-08-01",
    execution_note: "Prestation réalisée du 01/06 au 30/06/2026",
    lines: [
      line("l1", "prd-1", "Développement du module logistique", 12, 2500000, 18),
      line("l2", "prd-5", "Formation des équipes terrain", 2, 1200000, 0),
    ],
    status: "acceptee",
    etva_status: "accepte",
    etva_reference: "DEMO-REF-000001",
    etva_message: "Transmission simulée acceptée (mode démonstration).",
    created_at: "2026-07-02T09:12:00Z",
    history: [
      { id: "h1", label: "Facture créée", at: "2026-07-02T09:12:00Z", user: "Mamadou Barry" },
      { id: "h2", label: "Facture validée", at: "2026-07-02T10:02:00Z", user: "Mamadou Barry" },
      {
        id: "h3",
        label: "Transmission eTVA (simulation) acceptée",
        at: "2026-07-02T10:05:00Z",
        user: "Mamadou Barry",
      },
    ],
  },
  {
    id: "inv-2",
    company_id: COMPANY_ID,
    document_type: "facture",
    parent_invoice_id: null,
    reference: "FACT-2026-0002",
    internal_reference: "CMD-TG-078",
    customer_id: "cus-2",
    billing_setting_id: "bst-1",
    issue_date: "2026-08-14",
    due_date: "2026-09-13",
    execution_note: "Maintenance juillet 2026",
    lines: [line("l3", "prd-2", "Maintenance logicielle — juillet", 1, 4500000, 18)],
    status: "validee",
    etva_status: "non_transmis",
    etva_reference: null,
    etva_message: null,
    created_at: "2026-08-14T11:40:00Z",
    history: [
      { id: "h4", label: "Facture créée", at: "2026-08-14T11:40:00Z", user: "Mamadou Barry" },
      { id: "h5", label: "Facture validée", at: "2026-08-14T12:05:00Z", user: "Fatima Sow" },
    ],
  },
  {
    id: "inv-3",
    company_id: COMPANY_ID,
    document_type: "facture",
    parent_invoice_id: null,
    reference: "FACT-2026-0003",
    internal_reference: "CMD-CAP-002",
    customer_id: "cus-3",
    billing_setting_id: "bst-1",
    issue_date: "2026-09-01",
    due_date: "2026-10-01",
    execution_note: "",
    lines: [
      line("l4", "prd-3", "Ordinateurs portables — dotation service admin", 4, 12500000, 18),
      line("l5", "prd-4", "Licences bureautiques", 4, 1800000, 18),
    ],
    status: "brouillon",
    etva_status: "non_transmis",
    etva_reference: null,
    etva_message: null,
    created_at: "2026-09-01T08:20:00Z",
    history: [
      { id: "h6", label: "Facture créée", at: "2026-09-01T08:20:00Z", user: "Mamadou Barry" },
    ],
  },
  {
    id: "inv-4",
    company_id: COMPANY_ID,
    document_type: "facture",
    parent_invoice_id: null,
    reference: "FACT-2026-0004",
    internal_reference: "CMD-SMB-015",
    customer_id: "cus-1",
    billing_setting_id: "bst-2",
    issue_date: "2026-09-08",
    due_date: "2026-10-23",
    execution_note: "Livraison export",
    lines: [line("l6", "prd-3", "Ordinateurs portables — site Boké", 6, 12500000, 0)],
    status: "rejetee",
    etva_status: "rejete",
    etva_reference: null,
    etva_message:
      "Rejet simulé : le NIFp du client doit être vérifié avant transmission (mode démonstration, aucun échange réel avec la DGI).",
    created_at: "2026-09-08T15:02:00Z",
    history: [
      { id: "h7", label: "Facture créée", at: "2026-09-08T15:02:00Z", user: "Mamadou Barry" },
      { id: "h8", label: "Facture validée", at: "2026-09-08T15:20:00Z", user: "Mamadou Barry" },
      {
        id: "h9",
        label: "Transmission eTVA (simulation) rejetée",
        at: "2026-09-08T15:22:00Z",
        user: "Mamadou Barry",
      },
    ],
  },
  {
    id: "cn-1",
    company_id: COMPANY_ID,
    document_type: "avoir",
    parent_invoice_id: "inv-1",
    reference: "AVOIR-2026-0001",
    internal_reference: "AV-SMB-014",
    customer_id: "cus-1",
    billing_setting_id: "bst-1",
    issue_date: "2026-07-20",
    due_date: "2026-07-20",
    execution_note: "Régularisation d'une journée facturée en trop",
    lines: [line("l7", "prd-1", "Régularisation — 1 jour/homme", 1, 2500000, 18)],
    status: "acceptee",
    etva_status: "accepte",
    etva_reference: "DEMO-REF-000002",
    etva_message: "Transmission simulée acceptée (mode démonstration).",
    created_at: "2026-07-20T09:00:00Z",
    history: [
      {
        id: "h10",
        label: "Avoir créé depuis FACT-2026-0001",
        at: "2026-07-20T09:00:00Z",
        user: "Fatima Sow",
      },
      {
        id: "h11",
        label: "Transmission eTVA (simulation) acceptée",
        at: "2026-07-20T09:30:00Z",
        user: "Fatima Sow",
      },
    ],
  },
];

export const demoTransmissions: EtvaTransmission[] = [
  {
    id: "tr-1",
    invoice_id: "inv-1",
    invoice_reference: "FACT-2026-0001",
    document_type: "facture",
    sent_at: "2026-07-02T10:05:00Z",
    status: "accepte",
    dgi_reference: "DEMO-REF-000001",
    message: "Transmission simulée acceptée (mode démonstration).",
    http_status: 200,
    duration_ms: 842,
    operation: "transmission_facture",
    mode: "simulation",
  },
  {
    id: "tr-2",
    invoice_id: "cn-1",
    invoice_reference: "AVOIR-2026-0001",
    document_type: "avoir",
    sent_at: "2026-07-20T09:30:00Z",
    status: "accepte",
    dgi_reference: "DEMO-REF-000002",
    message: "Transmission simulée acceptée (mode démonstration).",
    http_status: 200,
    duration_ms: 611,
    operation: "transmission_avoir",
    mode: "simulation",
  },
  {
    id: "tr-3",
    invoice_id: "inv-4",
    invoice_reference: "FACT-2026-0004",
    document_type: "facture",
    sent_at: "2026-09-08T15:22:00Z",
    status: "rejete",
    dgi_reference: null,
    message: "Rejet simulé : NIFp client à vérifier (mode démonstration).",
    http_status: 422,
    duration_ms: 1204,
    operation: "transmission_facture",
    mode: "simulation",
  },
];

export const demoAudit: AuditEntry[] = [
  {
    id: "aud-1",
    user: "Mamadou Barry",
    action: "Création de facture",
    target: "FACT-2026-0004",
    at: "2026-09-08T15:02:00Z",
    result: "succes",
  },
  {
    id: "aud-2",
    user: "Mamadou Barry",
    action: "Transmission eTVA (simulation)",
    target: "FACT-2026-0004",
    at: "2026-09-08T15:22:00Z",
    result: "echec",
  },
  {
    id: "aud-3",
    user: "Fatima Sow",
    action: "Modification du client",
    target: "Télécom Guinée SA",
    at: "2026-09-05T09:10:00Z",
    result: "succes",
  },
  {
    id: "aud-4",
    user: "Fatima Sow",
    action: "Création d'utilisateur",
    target: "Aïssatou Diallo",
    at: "2026-08-28T16:00:00Z",
    result: "succes",
  },
  {
    id: "aud-5",
    user: "Mamadou Barry",
    action: "Création d'avoir",
    target: "AVOIR-2026-0001",
    at: "2026-07-20T09:00:00Z",
    result: "succes",
  },
];

export const demoRevenueSeries = [
  { month: "Avr", ca: 48200000, tva: 8676000 },
  { month: "Mai", ca: 63400000, tva: 11412000 },
  { month: "Juin", ca: 51900000, tva: 9342000 },
  { month: "Juil", ca: 78600000, tva: 14148000 },
  { month: "Août", ca: 69300000, tva: 12474000 },
  { month: "Sept", ca: 92050000, tva: 16569000 },
];
